# Generated by Django 5.0.1 on 2024-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='NE', max_length=2, verbose_name='Тип публикации'),
        ),
    ]
